export const ADMIN_PASS  = 'ADMIN2024';
export const OWNER_PASS  = 'YOUNESMAMECHE123'; // your secret owner password - change this!
export const OWNER_WHATSAPP = '213557095489';   // your WhatsApp number (with country code, no +)
export const LOW_STOCK   = 5;

export const STORES = [
  { id: 's1', name: 'Main Branch',    code: 'MAIN01' },
  { id: 's2', name: 'Downtown Store', code: 'DOWN02' },
  { id: 's3', name: 'Mall Kiosk',     code: 'MALL03' },
  { id: 's4', name: 'Hnout',     code: 'HANOUT1' },
];

export const PALETTE = [
  { name:'White',    hex:'#f5f5f0' }, { name:'Cream',    hex:'#fef3c7' },
  { name:'Beige',    hex:'#e8d5b7' }, { name:'Yellow',   hex:'#fbbf24' },
  { name:'Orange',   hex:'#f97316' }, { name:'Rust',     hex:'#c2410c' },
  { name:'Red',      hex:'#dc2626' }, { name:'Pink',     hex:'#ec4899' },
  { name:'Rose',     hex:'#fb7185' }, { name:'Purple',   hex:'#9333ea' },
  { name:'Lavender', hex:'#a78bfa' }, { name:'Indigo',   hex:'#4338ca' },
  { name:'Navy',     hex:'#1e3a8a' }, { name:'Blue',     hex:'#3b82f6' },
  { name:'Sky',      hex:'#38bdf8' }, { name:'Teal',     hex:'#0d9488' },
  { name:'Green',    hex:'#16a34a' }, { name:'Olive',    hex:'#65803d' },
  { name:'Khaki',    hex:'#c4b070' }, { name:'Camel',    hex:'#c4995a' },
  { name:'Brown',    hex:'#92400e' }, { name:'Grey',     hex:'#9ca3af' },
  { name:'Charcoal', hex:'#374151' }, { name:'Black',    hex:'#111827' },
  { name:'Silver',   hex:'#cbd5e1' }, { name:'Gold',     hex:'#d4a017' },
  { name:'Denim',    hex:'#5b7fa6' }, { name:'Coral',    hex:'#ff6b6b' },
  { name:'Mint',     hex:'#6ee7b7' }, { name:'Lilac',    hex:'#c084fc' },
];

export const SIZES = ['XS','S','M','L','XL','XXL','28','30','32','34','36','38','6','7','8','9','10','11'];
export const CATEGORIES = ['Tops','Bottoms','Dresses','Outerwear','Shoes','Accessories'];

export const PLANS = {
  free: {
    id: 'free', name: 'Free', nameFr: 'Gratuit', nameAr: 'مجاني',
    price: 0, color: '#6b7280', gradient: 'linear-gradient(135deg,#6b7280,#4b5563)',
    limits: { stores:1, products:30, csvExport:false, visualSearch:false },
    features: ['1 store','Up to 30 products','Basic inventory'],
    missing: ['CSV export','Photo search','Multiple stores'],
  },
  standard: {
    id: 'standard', name: 'Standard', nameFr: 'Standard', nameAr: 'قياسي',
    price: 990, color: '#4f46e5', gradient: 'linear-gradient(135deg,#4f46e5,#7c3aed)',
    limits: { stores:3, products:Infinity, csvExport:true, visualSearch:true },
    features: ['Up to 3 stores','Unlimited products','CSV export','Photo search (AI)'],
    missing: ['Unlimited stores'],
  },
  pro: {
    id: 'pro', name: 'Pro', nameFr: 'Pro', nameAr: 'احترافي',
    price: 2490, color: '#059669', gradient: 'linear-gradient(135deg,#059669,#0d9488)',
    limits: { stores:Infinity, products:Infinity, csvExport:true, visualSearch:true },
    features: ['Unlimited stores','Unlimited products','CSV export','Photo search (AI)','Priority support'],
    missing: [],
  },
};

export const T = {
  en: {
    dir: 'ltr', lang: 'en',
    appName: 'Store Inventory',
    tagline: 'Prices · Stock · Colors · Sizes',
    products: 'Products', outOfStock: 'Out of Stock', lowStock: 'Low Stock', today: 'Today',
    inventory: 'Inventory', salesHistory: 'Sales',
    search: 'Search products…', allCategories: 'All Categories', allStock: 'All Stock',
    inStock: 'In Stock', low: 'Low Stock', out: 'Out of Stock',
    newProduct: '+ New Product', searchByPhoto: 'Search by Photo',
    addProduct: 'Add Product', editProduct: 'Edit Product',
    productName: 'Product Name *', price: 'Price (DA) *', category: 'Category',
    colorsAndSizes: 'Colors & Sizes', pickColor: 'Pick a color', addColor: 'Add Color',
    addSize: '+ Add Size', createProduct: 'Create Product', saveChanges: 'Save Changes',
    cancel: 'Cancel', delete: 'Delete', remove: 'Remove',
    deleteProduct: 'Delete Product', deleteConfirm: 'This will permanently remove',
    photo: 'Photo', camera: 'Camera', gallery: 'Gallery', removePhoto: 'Remove photo',
    recordSale: 'Record Sale', sale: '🛍️ Sale', stock: 'Stock', edit: '✏️ Edit',
    stockBreakdown: 'STOCK — tap qty to edit',
    color: 'Color', size: 'Size', qty: 'Quantity Sold', salePrice: 'Sale Price (DA)',
    original: 'Original', note: 'Note (optional)', notePlaceholder: 'e.g. loyal customer…',
    totalCollect: 'Total to collect', confirmSale: 'Confirm Sale',
    noVariants: 'No variants. Edit the product first.',
    fullPrice: 'Full price',
    takePhoto: 'Take Photo', fromGallery: 'From Gallery', opensCamera: 'Opens camera', chooseExisting: 'Choose existing',
    retake: '📷 Retake',
    findProduct: '🔍 Find this product', analyzing: 'Analyzing photo…', comparingWith: 'Comparing with',
    matchFound: 'Match found!', goToProduct: '→ Go to product', tryAgain: 'Try again', tryAnotherPhoto: 'Try another photo',
    noMatch: 'No match found. Try a closer or clearer photo.', analyzeError: 'Could not analyze. Try again.',
    revenue: 'Revenue', itemsSold: 'Items Sold', transactions: 'Transactions',
    noSalesYet: 'No sales recorded yet.', noSalesPeriod: 'No sales in this period.',
    all: 'All', todayFilter: 'Today', sevenDays: '7 days',
    exportCSV: '⬇️ Export CSV', clearAll: '🗑️ Clear All', clearConfirm: 'Clear all sales history? Cannot be undone.',
    date: 'Date', product: 'Product', colorSize: 'Color / Size', unitPrice: 'Unit Price', total: 'Total',
    logOut: '⬅️ Log Out', synced: '✓ Synced', saving: '⟳ Saving…', saveFailed: '⚠️ Save failed',
    noProductsYet: 'No products yet. Add your first one!', noResults: 'No products matching',
    addFirst: '+ Add Product',
    enterCode: 'Enter your store access code', accessCode: 'Access Code', enterStore: 'Enter Store',
    invalidCode: 'Invalid access code. Check with your manager.',
    adminAccess: 'Admin Access', adminPanel: '🔐 Admin Panel', adminTagline: 'stores · live data',
    password: 'Password', wrongPassword: 'Wrong password.', enter: 'Enter',
    backToLogin: '← Back to login', back: '← Back', refresh: '🔄 Refresh', allStores: 'All Stores',
    revenue2: 'Revenue', totalProducts: 'Total Products', totalRevenue: 'Total Revenue', todayRevenue: "Today's Revenue",
    totalSales: 'Total Sales', noProductsAdmin: 'No products yet.', noSalesAdmin: 'No sales yet.',
    exportStore: 'Export CSV', addStoreTip: 'To add stores: edit the STORES array in src/config.js',
    soldToast: 'sold for', addedToast: 'added.', deletedToast: 'Product deleted.',
    returnBtn: 'Return', returned: 'Returned', returnTitle: 'Process Return',
    returnQty: 'Qty to return', returnRefund: 'Refund amount',
    returnNote: 'Stock will be restored automatically.',
    confirmReturn: 'Confirm Return', returnedToast: 'returned — stock restored',
    categories: ['All','Tops','Bottoms','Dresses','Outerwear','Shoes','Accessories'],
  },
  fr: {
    dir: 'ltr', lang: 'fr',
    appName: 'Inventaire', tagline: 'Prix · Stock · Couleurs · Tailles',
    products: 'Produits', outOfStock: 'Rupture', lowStock: 'Stock faible', today: "Aujourd'hui",
    inventory: 'Inventaire', salesHistory: 'Ventes',
    search: 'Rechercher…', allCategories: 'Toutes catégories', allStock: 'Tout le stock',
    inStock: 'En stock', low: 'Stock faible', out: 'Rupture',
    newProduct: '+ Nouveau', searchByPhoto: 'Recherche par photo',
    addProduct: 'Ajouter un produit', editProduct: 'Modifier le produit',
    productName: 'Nom du produit *', price: 'Prix (DA) *', category: 'Catégorie',
    colorsAndSizes: 'Couleurs & Tailles', pickColor: 'Choisir une couleur', addColor: 'Ajouter couleur',
    addSize: '+ Ajouter taille', createProduct: 'Créer', saveChanges: 'Enregistrer',
    cancel: 'Annuler', delete: 'Supprimer', remove: 'Retirer',
    deleteProduct: 'Supprimer le produit', deleteConfirm: 'Suppression définitive de',
    photo: 'Photo', camera: 'Caméra', gallery: 'Galerie', removePhoto: 'Supprimer la photo',
    recordSale: 'Vente', sale: '🛍️ Vente', stock: 'Stock', edit: '✏️ Modifier',
    stockBreakdown: 'STOCK — appuyer pour modifier',
    color: 'Couleur', size: 'Taille', qty: 'Quantité vendue', salePrice: 'Prix de vente (DA)',
    original: 'Original', note: 'Note (optionnel)', notePlaceholder: 'ex: client fidèle…',
    totalCollect: 'Total à encaisser', confirmSale: 'Confirmer la vente',
    noVariants: 'Aucune variante. Modifiez le produit.',
    fullPrice: 'Prix plein',
    takePhoto: 'Prendre photo', fromGallery: 'Galerie', opensCamera: 'Ouvre la caméra', chooseExisting: 'Choisir existante',
    retake: '📷 Reprendre',
    findProduct: '🔍 Trouver ce produit', analyzing: 'Analyse en cours…', comparingWith: 'Comparaison avec',
    matchFound: 'Correspondance !', goToProduct: '→ Voir le produit', tryAgain: 'Réessayer', tryAnotherPhoto: 'Autre photo',
    noMatch: 'Aucune correspondance. Essayez une photo plus nette.', analyzeError: 'Erreur analyse. Réessayez.',
    revenue: 'Revenu', itemsSold: 'Articles vendus', transactions: 'Transactions',
    noSalesYet: 'Aucune vente enregistrée.', noSalesPeriod: 'Aucune vente sur cette période.',
    all: 'Tout', todayFilter: "Aujourd'hui", sevenDays: '7 jours',
    exportCSV: '⬇️ Exporter CSV', clearAll: '🗑️ Tout effacer', clearConfirm: 'Effacer tout? Irréversible.',
    date: 'Date', product: 'Produit', colorSize: 'Couleur / Taille', unitPrice: 'Prix unitaire', total: 'Total',
    logOut: '⬅️ Déconnexion', synced: '✓ Synchronisé', saving: '⟳ Enregistrement…', saveFailed: '⚠️ Échec sauvegarde',
    noProductsYet: 'Aucun produit. Ajoutez le premier !', noResults: 'Aucun produit pour',
    addFirst: '+ Ajouter',
    enterCode: 'Entrez votre code d\'accès', accessCode: 'Code d\'accès', enterStore: 'Entrer', invalidCode: 'Code invalide.',
    adminAccess: 'Accès admin', adminPanel: '🔐 Admin', adminTagline: 'magasins · données live',
    password: 'Mot de passe', wrongPassword: 'Mot de passe incorrect.', enter: 'Entrer',
    backToLogin: '← Retour', back: '← Retour', refresh: '🔄 Actualiser', allStores: 'Tous les magasins',
    revenue2: 'Revenu', totalProducts: 'Produits totaux', totalRevenue: 'Revenu total', todayRevenue: "Revenu aujourd'hui",
    totalSales: 'Ventes totales', noProductsAdmin: 'Aucun produit.', noSalesAdmin: 'Aucune vente.',
    exportStore: 'Exporter CSV', addStoreTip: 'Pour ajouter des magasins: modifier STORES dans src/config.js',
    soldToast: 'vendu pour', addedToast: 'ajouté.', deletedToast: 'Produit supprimé.',
    returnBtn: 'Retour', returned: 'Retourné', returnTitle: 'Traiter le retour',
    returnQty: 'Qté à retourner', returnRefund: 'Montant remboursé',
    returnNote: 'Le stock sera restauré automatiquement.',
    confirmReturn: 'Confirmer le retour', returnedToast: 'retourné — stock restauré',
    categories: ['Tout','Hauts','Bas','Robes','Manteaux','Chaussures','Accessoires'],
  },
  ar: {
    dir: 'rtl', lang: 'ar',
    appName: 'المخزون', tagline: 'أسعار · مخزون · ألوان · مقاسات',
    products: 'المنتجات', outOfStock: 'نفذ', lowStock: 'منخفض', today: 'اليوم',
    inventory: 'المخزون', salesHistory: 'المبيعات',
    search: 'بحث عن منتج…', allCategories: 'كل الفئات', allStock: 'كل المخزون',
    inStock: 'متوفر', low: 'منخفض', out: 'نفذ',
    newProduct: '+ منتج جديد', searchByPhoto: 'بحث بالصورة',
    addProduct: 'إضافة منتج', editProduct: 'تعديل المنتج',
    productName: 'اسم المنتج *', price: 'السعر (د.ج) *', category: 'الفئة',
    colorsAndSizes: 'الألوان والمقاسات', pickColor: 'اختر لوناً', addColor: 'إضافة لون',
    addSize: '+ إضافة مقاس', createProduct: 'إنشاء المنتج', saveChanges: 'حفظ',
    cancel: 'إلغاء', delete: 'حذف', remove: 'إزالة',
    deleteProduct: 'حذف المنتج', deleteConfirm: 'سيتم حذف',
    photo: 'صورة', camera: 'كاميرا', gallery: 'المعرض', removePhoto: 'إزالة الصورة',
    recordSale: 'تسجيل بيع', sale: '🛍️ بيع', stock: 'المخزون', edit: '✏️ تعديل',
    stockBreakdown: 'المخزون — اضغط للتعديل',
    color: 'اللون', size: 'المقاس', qty: 'الكمية المباعة', salePrice: 'سعر البيع (د.ج)',
    original: 'الأصلي', note: 'ملاحظة', notePlaceholder: 'مثال: خصم عميل…',
    totalCollect: 'المبلغ الإجمالي', confirmSale: 'تأكيد البيع',
    noVariants: 'لا توجد متغيرات. عدّل المنتج أولاً.',
    fullPrice: 'السعر الكامل',
    takePhoto: 'التقط صورة', fromGallery: 'من المعرض', opensCamera: 'يفتح الكاميرا', chooseExisting: 'اختر صورة',
    retake: '📷 إعادة',
    findProduct: '🔍 ابحث عن المنتج', analyzing: 'جاري التحليل…', comparingWith: 'مقارنة مع',
    matchFound: 'تم العثور على تطابق!', goToProduct: '← الذهاب للمنتج', tryAgain: 'حاول مجدداً', tryAnotherPhoto: 'صورة أخرى',
    noMatch: 'لم يُعثر على تطابق. جرب صورة أوضح.', analyzeError: 'فشل التحليل. حاول مجدداً.',
    revenue: 'الإيرادات', itemsSold: 'مبيعات', transactions: 'المعاملات',
    noSalesYet: 'لا توجد مبيعات مسجلة.', noSalesPeriod: 'لا توجد مبيعات في هذه الفترة.',
    all: 'الكل', todayFilter: 'اليوم', sevenDays: '7 أيام',
    exportCSV: '⬇️ تصدير CSV', clearAll: '🗑️ مسح الكل', clearConfirm: 'مسح كل المبيعات؟ لا يمكن التراجع.',
    date: 'التاريخ', product: 'المنتج', colorSize: 'اللون / المقاس', unitPrice: 'سعر الوحدة', total: 'المجموع',
    logOut: 'خروج ⬅️', synced: '✓ متزامن', saving: '⟳ جاري الحفظ…', saveFailed: '⚠️ فشل الحفظ',
    noProductsYet: 'لا توجد منتجات. أضف أول منتج!', noResults: 'لا توجد منتجات تطابق',
    addFirst: '+ إضافة منتج',
    enterCode: 'أدخل رمز الوصول الخاص بمتجرك', accessCode: 'رمز الوصول', enterStore: 'دخول', invalidCode: 'رمز غير صحيح.',
    adminAccess: 'دخول المدير', adminPanel: '🔐 لوحة الإدارة', adminTagline: 'متاجر · بيانات مباشرة',
    password: 'كلمة المرور', wrongPassword: 'كلمة المرور غير صحيحة.', enter: 'دخول',
    backToLogin: 'العودة →', back: 'العودة →', refresh: '🔄 تحديث', allStores: 'جميع المتاجر',
    revenue2: 'الإيرادات', totalProducts: 'إجمالي المنتجات', totalRevenue: 'إجمالي الإيرادات', todayRevenue: 'إيرادات اليوم',
    totalSales: 'إجمالي المبيعات', noProductsAdmin: 'لا توجد منتجات.', noSalesAdmin: 'لا توجد مبيعات.',
    exportStore: 'تصدير CSV', addStoreTip: 'لإضافة متاجر: عدّل مصفوفة STORES في src/config.js',
    soldToast: 'بيع بـ', addedToast: 'تمت الإضافة.', deletedToast: 'تم حذف المنتج.',
    returnBtn: 'إرجاع', returned: 'مُرجَع', returnTitle: 'معالجة الإرجاع',
    returnQty: 'الكمية المُرجَعة', returnRefund: 'مبلغ الاسترداد',
    returnNote: 'سيتم استعادة المخزون تلقائياً.',
    confirmReturn: 'تأكيد الإرجاع', returnedToast: 'تم الإرجاع — تمت استعادة المخزون',
    categories: ['الكل','قمم','سراويل','فساتين','معاطف','أحذية','إكسسوارات'],
  },
};
